name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Printing image name
      run: 

    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_TOKEN }}/transpilation:latest .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Pushing Docker images to docker hub
      run : docker push ${{ secrets.DOCKERHUB_TOKEN }}/transpilation:latest
      

